CREATE TABLE SSH_PERSON
(
PERSON_FLDID NUMBER PRIMARY KEY,
PERSON_FLDCODE VARCHAR2(64),
PERSON_FLDNAME VARCHAR2(64),
PERSON_FLDDEPART NUMBER,
PERSON_FLDDUTY NUMBER,
PERSOPN_FLDCREATEDATE DATE DEFAULT SYSDATE,
PERSON_FLDCONTENT VARCHAR2(2048),
CONSTRAINTS FK_PERSON_DEPT FOREIGN KEY (PERSON_FLDDEPART) REFERENCES SYS_DICT (DICT_FLDID),
CONSTRAINTS FK_PERSON_DUTY FOREIGN KEY (PERSON_FLDDUTY) REFERENCES SYS_DICT (DICT_FLDID)
);

CREATE TABLE SSH_BUILDING
(
BUILD_FLDID NUMBER PRIMARY KEY,
BUILD_FLDNAME VARCHAR2(64),
BUILD_FLDGENDER NUMBER,
BUILD_CONTENT VARCHAR2(2048),
CONSTRAINTS FK_BUILD_GENDER FOREIGN KEY (BUILD_FLDGENDER) REFERENCES SYS_DICT (DICT_FLDID)
);

CREATE TABLE SSH_ROOM
(
ROOM_FLDID NUMBER PRIMARY KEY,
ROOM_FLDCODE VARCHAR2(64),
ROOM_FLDBUILDID NUMBER,
CONSTRAINTS FK_ROOM_BUILD FOREIGN KEY (ROOM_FLDBUILDID) REFERENCES SSH_BUILDING (BUILD_FLDID)

);


CREATE TABLE SSH_GOODS
(
GOODS_FLDID NUMBER PRIMARY KEY,
GOODS_FLDTYPE NUMBER ,
GOODS_FLDCODE VARCHAR2(1024),
GOODS_FLDROOMID NUMBER,
GOODS_FLDPERSONID NUMBER,
GOODS_USERDATE VARCHAR2(64),
GOODS_CREATEDATE DATE DEFAULT SYSDATE,
GOODS_STATUS NUMBER,
GOODS_CONTENT VARCHAR2(1024),
CONSTRAINTS FK_GOODS_TYPE FOREIGN KEY (GOODS_FLDTYPE) REFERENCES SYS_DICT (DICT_FLDID),
CONSTRAINTS FK_GOODS_ROOMID FOREIGN KEY (GOODS_FLDROOMID) REFERENCES SSH_ROOM (ROOM_FLDID),
CONSTRAINTS FK_GOODS_PERSONID FOREIGN KEY (GOODS_FLDPERSONID) REFERENCES SSH_PERSON (PERSON_FLDID),
CONSTRAINTS FK_GOODS_STATUS FOREIGN KEY (GOODS_STATUS) REFERENCES SYS_DICT (DICT_FLDID)
);


CREATE TABLE SSH_BORROW
(
BORROW_FLDID NUMBER PRIMARY KEY,
BORROW_FLDOPERTYPE NUMBER,
BORROW_FLDOBEJCTID NUMBER,
BORROW_FLDBORROWPERSONID NUMBER,
BORROW_FLDBEGINDATE VARCHAR2(64),
BORROW_FLDENDDATE VARCHAR2(64),
BORROW_FLDCONTENT VARCHAR2(2048),
CONSTRAINTS FK_BORROW_OPERTYPE FOREIGN KEY (BORROW_FLDOPERTYPE) REFERENCES SYS_DICT (DICT_FLDID),
CONSTRAINTS FK_BORROW_OBEJCTID FOREIGN KEY (BORROW_FLDOBEJCTID) REFERENCES SSH_GOODS (GOODS_FLDID),
CONSTRAINTS FK_BORROW_BORROWPERSONID FOREIGN KEY (BORROW_FLDBORROWPERSONID) REFERENCES SSH_PERSON (PERSON_FLDID)
);

CREATE TABLE SSH_BREAKRULE
(
BREAKRULE_FLDID NUMBER PRIMARY KEY,
BREAKRULE_FLDOPTPERSONID NUMBER,
BREAKRULE_FLDOBJECTTYPE NUMBER ,
BREAKRULE_FLDRESON VARCHAR2(2048),
BREAKRULE_FLDFINE VARCHAR2(64),
BREAKRULE_FLDOCCURDATE VARCHAR2(64),
BREAKRULE_FLDCONTENT VARCHAR2(2048),
CONSTRAINTS FK_BREAKRULE_PERSON FOREIGN KEY (BREAKRULE_FLDOPTPERSONID) REFERENCES SSH_PERSON (PERSON_FLDID),
CONSTRAINTS FK_BREAKRULE_OBJECTTYPE FOREIGN KEY (BREAKRULE_FLDOBJECTTYPE) REFERENCES SYS_DICT (DICT_FLDID) 
);

            


