CREATE TABLE SYS_USER
(
FLDID NUMBER PRIMARY KEY,
FLDCODE VARCHAR2(64),
FLDNAME VARCHAR2(64),
FLDDICTID NUMBER,
FLDPASS VARCHAR2(64),
FLDPHONE VARCHAR2(64),
FLDMAIL VARCHAR2(64),
FLDDEPARTMENTID NUMBER,
FLDCREATEDATE DATE DEFAULT SYSDATE,
FLDVALIDDATE DATE,
CONSTRAINTS FK_DICT FOREIGN KEY (FLDDICTID) REFERENCES SYS_DICT(FLDID)
);

CREATE TABLE SYS_DICT
(
FLDID NUMBER PRIMARY KEY,
FLDNAME VARCHAR2(64),
FLDTYPE VARCHAR2(64)
)

CREATE SEQUENCE SEQ_DICT
MINVALUE 0

INSERT INTO SYS_DICT VALUES(SEQ_DICT.NEXTVAL,'男','性别');
INSERT INTO SYS_DICT VALUES(SEQ_DICT.NEXTVAL,'女','性别');

SELECT * FROM SYS_DICT

SELECT * FROM SYS_USER 


CREATE SEQUENCE SEQ_USER 
MINVALUE 0


INSERT INTO SYS_USER VALUES(SEQ_USER.NEXTVAL,'RSBADMIN','管理员',2,'rsbadmin','12345','12345@12345.com',1,DEFAULT,SYSDATE);

INSERT INTO SYS_USER VALUES(SEQ_USER.NEXTVAL,'RSBZONGWU','总务',2,'rsbzongwu','12345','12346@12346.com',2,DEFAULT,SYSDATE);

INSERT INTO SYS_USER VALUES(SEQ_USER.NEXTVAL,'RSBRENSHI','人事',2,'rsbrenshi','12345','12347@12347.com',3,DEFAULT,SYSDATE);


CREATE TABLE SYS_ROLE
(
FLDID NUMBER PRIMARY KEY,
FLDNAME VARCHAR2(64),
FLDDES VARCHAR2(64)
);

CREATE SEQUENCE SEQ_ROLEID
MINVALUE 0

SELECT * FROM SYS_ROLE

INSERT INTO SYS_ROLE VALUES(SEQ_ROLEID.NEXTVAL,'ADMIN','最高管理员');
INSERT INTO SYS_ROLE VALUES(SEQ_ROLEID.NEXTVAL,'MANAGER','管理员');
INSERT INTO SYS_ROLE VALUES(SEQ_ROLEID.NEXTVAL,'NORMAL','普通用户');


CREATE TABLE SYS_USER_VS_ROLE
(
FLD_USER_ID NUMBER,
FLD_ROLE_ID NUMBER,
CONSTRAINTS FK_USER FOREIGN KEY (FLD_USER_ID) REFERENCES SYS_USER(FLDID),
CONSTRAINTS FK_ROLE FOREIGN KEY (FLD_ROLE_ID) REFERENCES SYS_ROLE(FLDID)
);

SELECT * FROM SYS_USER;
SELECT * FROM SYS_ROLE;

INSERT INTO SYS_USER_VS_ROLE VALUES(1,1);
INSERT INTO SYS_USER_VS_ROLE VALUES(1,2);
INSERT INTO SYS_USER_VS_ROLE VALUES(1,3);
INSERT INTO SYS_USER_VS_ROLE VALUES(2,2);
INSERT INTO SYS_USER_VS_ROLE VALUES(2,3);
INSERT INTO SYS_USER_VS_ROLE VALUES(3,3);


SELECT * FROM SYS_USER_VS_ROLE


CREATE TABLE SYS_ROLE_GROUP
(
FLDID NUMBER PRIMARY KEY,
FLDNAME VARCHAR2(64),
FLDDESC VARCHAR2(64)
);

CREATE SEQUENCE SEQ_ROLEGROUP
MINVALUE 0

INSERT INTO SYS_ROLE_GROUP VALUES(SEQ_ROLEGROUP.NEXTVAL,'管理员','管理员组');
INSERT INTO SYS_ROLE_GROUP VALUES(SEQ_ROLEGROUP.NEXTVAL,'普通用户','普通用户组');

SELECT * FROM SYS_ROLE_GROUP;
SELECT * FROM SYS_USER

CREATE TABLE SYS_USER_VS_GROUP
(
FLD_USER_ID NUMBER,
FLD_GROUP_ID NUMBER,
CONSTRAINTS FK_USER_ID FOREIGN KEY (FLD_USER_ID) REFERENCES SYS_USER(FLDID),
CONSTRAINTS FK_GROUP_ID FOREIGN KEY (FLD_GROUP_ID) REFERENCES SYS_ROLE_GROUP(FLDID)
);

INSERT INTO SYS_USER_VS_GROUP VALUES(1,1);
INSERT INTO SYS_USER_VS_GROUP VALUES(2,1);
INSERT INTO SYS_USER_VS_GROUP VALUES(3,2);

CREATE TABLE SYS_DEPARTMENT
(
FLDID NUMBER PRIMARY KEY,
FLDDEPARTMNET VARCHAR2(64),
FLDGROUPROLEID NUMBER,
CONSTRAINTS FK_DEPT FOREIGN KEY (FLDGROUPROLEID) REFERENCES SYS_ROLE_GROUP (FLDID) 
);

CREATE SEQUENCE SEQ_DEPT
MINVALUE 0

INSERT INTO  SYS_DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL,'IDE',1);
INSERT INTO SYS_DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL,'总务',1);
INSERT INTO SYS_DEPARTMENT VALUES(SEQ_DEPT.NEXTVAL,'人事',2);

ALTER TABLE SYS_USER
ADD CONSTRAINTS FK_USER_DEPT FOREIGN KEY (FLDDEPARTMENTID) REFERENCES SYS_DEPARTMENT(FLDID)


CREATE TABLE SYS_GROUP_VS_ROLE
(
FLD_ROLE_ID NUMBER,
FLD_GROUP_ID NUMBER,
CONSTRAINTS FK_RG FOREIGN KEY (FLD_ROLE_ID) REFERENCES SYS_ROLE(FLDID),
CONSTRAINTS FK_GG FOREIGN KEY (FLD_GROUP_ID) REFERENCES SYS_ROLE_GROUP(FLDID)
);

SELECT * FROM SYS_ROLE;
SELECT * FROM SYS_ROLE_GROUP


INSERT INTO SYS_GROUP_VS_ROLE VALUES(1,1);
INSERT INTO SYS_GROUP_VS_ROLE VALUES(2,1);
INSERT INTO SYS_GROUP_VS_ROLE VALUES(3,2);


CREATE TABLE SYS_FUNCTION
(
FLDID NUMBER PRIMARY KEY,
FLDNAME VARCHAR2(20),
FLDISMEUN NUMBER,
FLDPARENTID NUMBER,
FLDURL VARCHAR2(1024),
FLDIMAG VARCHAR2(64),
FLDGROUP VARCHAR2(64),
FLDORDER NUMBER
);


CREATE SEQUENCE SEQ_FUNC
MINVALUE 0

CREATE TABLE SYS_ROLE_VS_FUNCTION
(
FLD_FUNC_ID NUMBER,
FLD_ROLE_ID NUMBER ,
CONSTRAINTS FK_FUNC_ID FOREIGN KEY (FLD_FUNC_ID) REFERENCES SYS_FUNCTION(FLDID),
CONSTRAINTS FK_RF FOREIGN KEY (FLD_ROLE_ID) REFERENCES SYS_ROLE(FLDID)
);

SELECT * FROM SYS_FUNCTION


INSERT INTO SYS_FUNCTION VALUES(SEQ_FUNC.NEXTVAL,'宿舍调配',1,6,'','','',7);
INSERT INTO SYS_FUNCTION VALUES(SEQ_FUNC.NEXTVAL,'员工借用',1,6,'','','',8);
INSERT INTO SYS_FUNCTION VALUES(SEQ_FUNC.NEXTVAL,'员工通报',1,6,'','','',9);
INSERT INTO SYS_FUNCTION VALUES(SEQ_FUNC.NEXTVAL,'闻博轩',1,6,'','','',10);
INSERT INTO SYS_FUNCTION VALUES(SEQ_FUNC.NEXTVAL,'静雅苑',1,6,'','','',11);


SELECT * FROM SYS_ROLE_VS_FUNCTION;

SELECT * FROM SYS_FUNCTION ;
SELECT * FROM SYS_ROLE


INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(1,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(2,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(3,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(4,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(5,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(6,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(7,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(8,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(9,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(10,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(11,1);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(1,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(2,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(3,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(4,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(6,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(7,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(8,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(9,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(10,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(11,2);
INSERT INTO SYS_ROLE_VS_FUNCTION VALUES(5,3);






